spring.application.name=HostelMgmt




#AWS Database configuration

#AWS Database configuration
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://fees.c9qk4g082ky0.ap-south-1.rds.amazonaws.com:3306/fees?ServerTimezone=UTC
#spring.datasource.username=admin
#spring.datasource.password=pjsofttechAWS
#server.port:29443
#server.ssl.key-store=/etc/letsencrypt/live/pjsofttech.in/pjsofttech.p12
#server.ssl.key-store-password=123456
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=pjsofttech.in
#server.ssl.enabled=true



#MySQL Database configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Hostel?ServerTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
server.port:9090




#Hibernate  Database configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.mvc.contentnegotiation.enabled=false




#Aws  images  configuration

aws.access-key=AKIA3FLD4DOERWWW4LVU
aws.secret-key=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
aws.s3.bucket-name=pjsofttech-docs
aws.region=us-east-1


#Aws  images Settings

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


# Email configuration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mustafapjsoftech@gmail.com
spring.mail.password=zrjcwtgejjcnugdw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=false



# Actuator health endpoint

management.endpoints.web.exposure.include=*
management.endpoints.health.show-details=always
management.endpoints.web.base-path=/admin





# Fixed Base URL (Optional, for clarity)
hostel.website.base-url=https://pjsofttech.in/hostel/website

spring.output.ansi.enabled=ALWAYS

